services:
  haproxy1:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy1
    volumes:
      - ./haproxy/keepalived-master.conf:/etc/keepalived/keepalived.conf
    depends_on:
      - backend1
      - backend2
    #network_mode: "host"
    privileged: true
    networks:
      haproxy_net:
        ipv4_address: 172.26.0.10
    #ports:
    #  - "81:80"

  haproxy2:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy2
    volumes:
      - ./haproxy/keepalived-backup.conf:/etc/keepalived/keepalived.conf
    depends_on:
      - backend1
      - backend2
    #network_mode: "host"
    privileged: true
    networks:
      haproxy_net:
        ipv4_address: 172.26.0.11
    #ports:
    #  - "82:80"

  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend1
    networks:
      haproxy_net:
        ipv4_address: 172.26.0.3
    ports:
      - "8081:80"

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    networks:
      haproxy_net:
        ipv4_address: 172.26.0.2
    ports:
      - "8082:80"

networks:
  haproxy_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
